apiVersion: apps/v1
kind: Deployment
metadata:
  name: # (my-app) app name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: # (Rajadurai/html-app) docker image url
        ports:
        - containerPort: 80
