apiVersion: v1
kind: Service
metadata:
  name: # (my-app) change app name here like in deployment.yaml file
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
